---
title: "Amy's Pre-Registration"
output: 
  html_document
bibliography: pre-registration.bib
csl: apa.csl
link-citations: true
editor_options: 
  markdown: 
    wrap: sentence
---
# Pre-registration Template 
Adapted from <https://osf.io/preprints/metaarxiv/epgjd> into markdown format.

<details>

-   [Study Information](#study-information)
    -   [1. Title](#1-title)
    -   [2. Authors](#2-authors)
    -   [3. Description](#3-description)
    -   [4. Hypotheses](#4-hypotheses)
-   [Design Plan](#design-plan)
    -   [5. Study type](#5-study-type)
    -   [6. Blinding](#6-blinding)
    -   [7. Is there any additional blinding in this study?](#7-is-there-any-additional-blinding-in-this-study-)
    -   [8. Study design](#8-study-design)
    -   [9. Randomization](#9-randomization)
-   [Sampling Plan](#sampling-plan)
    -   [10. Existing data](#10-existing-data)
    -   [11. Explanation of existing data](#11-explanation-of-existing-data)
    -   [12. Data collection procedures](#12-data-collection-procedures)
    -   [13. Sample size](#13-sample-size)
    -   [14. Sample size rationale](#14-sample-size-rationale)
    -   [15. Stopping rule](#15-stopping-rule)
-   [Variables](#variables)
    -   [16. Manipulated variables](#16-manipulated-variables)
    -   [17. Measured variables](#17-measured-variables)
    -   [18. Indices](#18-indices)
-   [Analysis Plan](#analysis-plan)
    -   [19. Statistical models](#19-statistical-models)
    -   [20. Transformations](#20-transformations)
    -   [21. Inference criteria](#21-inference-criteria)
    -   [22. Data exclusion](#22-data-exclusion)
    -   [23. Missing data](#23-missing-data)
    -   [24. Exploratory analysis](#24-exploratory-analysis)
-   [Other](#other)
    -   [25. Other](#25-other)

</details>

# Study Information {#study-information}

## 1. Title {#1-title}

> More Haste, Less Speed?
> Impact of Speed Listening on Attention

## 2. Authors {#2-authors}

Amy (Chuyue) Zhang

## 3. Description {#3-description}

In today’s world, much of our information access is through digital platforms.
With the ubiquitous use of portable devices and headphones, more and more learning is taking place in auditory formats: podcasts, audio books, lecture recording, even text-to-speed aids on the browser.
For more efficient learning, many people often speeding up their audios to save time, but this requires more effort for the listener.

Levels of processing theory posits that information retention will be better if the information is processed deeply and actively (e.g. thinking about meaning and connecting with other information) than passively (e.g. just reading or listening) [@craik_levels_1972].
The amount of information we are able to process and remember depends on the capacity of working memory [@craik_levels_1972].
But working memory can only process a certain amount of information at a given time – a limitation known as cognitive load [@sweller_cognitive_1998].
When information exceeds the storage capacity or processing ability of cognitive load, they are unable to retain and learn that information effectively [@paas_cognitive_2010].

Previous studies have found that audio speed of 2x or less generally does not impact information retention [@murphy_learning_2022], but only if the material is relatively easy to understand.
With higher speed or complexity, the cognitive load may become too high, and people cannot process and retain information as effectively [@krokar_effect_2023].
However, less is known about the impact of audio speed on attention of the listener, especially for extended amount of time.
Attention is often conceptualized as a resource of limited supply and plays an important role both in storing information in working memory and actively processing it [@oberauer_working_2019]
We learn better when we attend to it more carefully, but does audio speed has an impact on our ability to attend to information?
This study aims to investigate the impact of audio speed on listeners’ attention.

## 4. Hypotheses {#4-hypotheses}

Sustaining attention is effortful, therefore we should expect to see attention declining over time regardless of audio speed.

Since higher speed exerts a heavier cognitive load, the decline would be faster or occur earlier in faster speed conditions, i.e. 2.0x will decline faster than 1.75x, which will decline faster than 1.5x.

However, there is no clear direction of the attention level difference among different speed conditions.
As some research indicating higher speed had higher attention [@yang_time-compressed_2020], some indicating otherwise [@tran_examining_2024], the hypothesis about overall attention of each speed condition remains non-directional.

# Design Plan {#design-plan}

## 5. Study type {#5-study-type}

**Experiment** - A researcher randomly assigns treatments to study subjects, this includes field or lab experiments.
This is also known as an intervention experiment and includes randomized controlled trials.

## 6. Blinding {#6-blinding}

Blinding describes who is aware of the experimental manipulations within a study.
Mark all that apply.

-   [ ] No blinding is involved in this study.

-   [x] For studies that involve human subjects, they will not know the treatment group to which they have been assigned.

-   [ ] Personnel who interact directly with the study subjects (either human or non-human subjects) will not be aware of the assigned treatments.
    (Commonly known as “double blind”)

-   [ ] Personnel who analyze the data collected from the study are not aware of the treatment applied to any given group.

## 7. Is there any additional blinding in this study? {#7-is-there-any-additional-blinding-in-this-study-}

There is no additional blinding in this study.

## 8. Study design {#8-study-design}

A between-subject design will be used, considered the potentially strong carry-over effect of within-subject design for tasks involving sustained attention.
Upon starting the experiment, the participant will read a short introduction that outlines the experiment and provide brief instructions.
They will then listen to a 35-minute audio recording, with reaction time tasks embedded at various time points throughout the recording.
After the recording has finished playing, the participant will be asked to rate different aspects of their experience (described below).

The experiment has one independent variable – audio speed – at four levels (1.0x, 1.5x, 1.75x, 2.0x).
Participants will be randomly assigned to complete a listening task at one of the speed levels but will not be informed which level they are assigned to.

The dependent variable in the experiment is listeners’ attention, measured by accuracy and reaction times on sustained attention tasks that will appear throughout the audio recording.

At the end of the study, the participants will be asked to rate aspects of their experiences of speed listening on 7-point Likert scales. 

## 9. Randomization {#9-randomization}

This experiment will use simple random assignment, where each participant will be randomly assigned to one of the four speed levels by the experiment program.

# Sampling Plan {#sampling-plan}

## 10. Existing data {#10-existing-data}

Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data.
Therefore, creating a research plan in which existing data will be used presents unique challenges.
Please select the description that best describes your situation.
Please do not hesitate to contact us if you have questions about how to answer this question ([prereg\@cos.io](mailto:prereg@cos.io){.email}).

-   [x] Registration prior to creation of data: As of the date of submission of this research plan for preregistration, the data have not yet been collected, created, or realized.
-   [ ] Registration prior to any human observation of the data: As of the date of submission, the data exist but have not yet been quantified, constructed, observed, or reported by anyone - including individuals that are not associated with the proposed study. Examples include museum specimens that have not been measured and data that have been collected by non-human collectors and are inaccessible.
-   [ ] Registration prior to accessing the data: As of the date of submission, the data exist, but have not been accessed by you or your collaborators. Commonly, this includes data that has been collected by another researcher or institution.
-   [ ] Registration prior to analysis of the data: As of the date of submission, the data exist and you have accessed it, though no analysis has been conducted related to the research plan (including calculation of summary statistics). A common situation for this scenario when a large dataset exists that is used for many different studies over time, or when a data set is randomly split into a sample for exploratory analyses, and the other section of data is reserved for later confirmatory data analysis.
-   [ ] Registration following analysis of the data: As of the date of submission, you have accessed and analyzed some of the data relevant to the research plan. This includes preliminary analysis of variables, calculation of descriptive statistics, and observation of data distributions. Please see cos.io/prereg for more information.

## 11. Explanation of existing data {#11-explanation-of-existing-data}

There is no existing data for the study at the time of preregistration.

## 12. Data collection procedures {#12-data-collection-procedures}

Participants will be recruited in university classes through the university’s study recruitment system and posters.
Students in certain courses will receive course credit for completing the study; students outside the courses or participated after the courses have ended will receive $7 compensation.

All participants must have normal/corrected-to-normal vision and hearing, close-to-native fluency in English, and have access to headphones and a laptop with trackpad in order to participate in the study.

## 13. Sample size {#13-sample-size}

The target sample size is 76 people in total, with 19 people in each of the four audio speed levels.
We will attempt to recruit up to 90 people to account for potential dropouts and trials with incomplete data.

## 14. Sample size rationale {#14-sample-size-rationale}

We used R program to conduct a power analysis, with the desired power of 0.8 and a medium effect size of 0.5 (Cohen’s d), and the alpha level of 0.05.
```{r}
pwr::pwr.f2.test(u = 3, f2 = 0.15, power = 0.8, sig.level = 0.05)
```

## 15. Stopping rule {#15-stopping-rule}

Data collection will stop once the desired sample size of 90 is reached, after which no more sign-ups will be accepted from course sign-up and poster correspondence will be declined.

# Variables {#variables}

## 16. Manipulated variables {#16-manipulated-variables}

We manipulate the audio playback speed to generate four 25-minute-long audio clips.
This means that each clip will have a different word count.
The audios will be played at 1.0x, 1.5x, 1.75x, 2.0x speed levels.
These levels are common settings for audio platforms.
Since previous research has established that speed faster than 2.0x harms information retention, there is no ecological validity in speed levels higher than 2.0x.

We plan to use AI generated audio clips to better control for the content and speed.
The contents of the clips will be introductory information on science or social science concepts to avoid eliciting any personal emotions for the material.

The audio played across all trials will be adapted from the same script. The length of a typical lecture is 50 minutes, and the average speed of presentations and podcasts is around 150 words per minute ([Virture Speech](https://virtualspeech.com/blog/average-speaking-rate-words-per-minute)). We will generate a script of approximately 3,750 words and use AI to generate audios of various speed levels. The 2.0x speed audio will therefore contain the entire script and the 1.0x will contain approximately half of the same content.

## 17. Measured variables {#17-measured-variables}

The measured variable will be reaction time and response accuracy to attention check questions embedded within the audio clips.
The attention check questions will be spaced approximately five minutes apart, with a total of six time points for each condition; they will be content-related questions with obvious answers based on information given within the one minute prior to the attention check.
The response will require the participant to click one of several choices presented on the screen [@anwyl-irvine_mouseviewjs_2021], which will appear once the instruction/question is given in the audio, Participants’ reaction time will be recorded starting from the time the question appears on the screen.

Participants will be informed beforehand that they will receive questions about the content of the audio clip but will not be informed on the number or timing of the questions.

Sustained attention is usually measured using reaction time in visual response tasks, where participants are asked to make differential responses based on visual stimuli presented on screen [@rizzo_longitudinal_2022].
In research investigating the effectiveness of speed listening, participants usually respond to multiple choice questions about the content of audio recording as a measure of their information retention [@krokar_effect_2023].


After the speed listening, participants will  rate the following questions on a 7-point Likert scale:

- How well did you know the information just presented before taking part in the study?

- How much did you enjoy the content of the audio clip

- How focused do you think you were while listening to the audio clip

- How well do you think you have retained information from the audio clip

- How often do you speed listen in your own life?


## 18. Indices {#18-indices}

Reaction time and accuracy on attention check questions will be combined into one single measure for attention.

Since the attention check questions are designed to have obvious answers, we place to use inverse efficiency score (IES) to combine the two measurements [@liesefeld_combining_2019].

IES <- mean(RT) / mean(Accuracy)

# Analysis Plan {#analysis-plan}

## 19. Statistical models {#19-statistical-models}

The study will use a Mixed-Design ANOVA (Split-Plot ANOVA) to test whether changes in reaction time (dependent variable) differ between different audio speeds (independent variable) – with the four levels of audio speed as between-subject factor and the repeated time point measurement of reaction time as within-subjects factors.

If the assumptions of ANOVA are violated, Greenhouse-Geisser Correction will be performed to adjust degrees of freedom.

If the effect of audio speed is significant, post hoc tests such as Tukey's HSD (if equal variances are assumed) or Games-Howell Test (if homogeneity of variance is violated) will be performed.

If the difference between time points is significant, Bonferroni-corrected paired t-tests will be performed.

If there is interaction between time and audio speed levels, paired t-tests will be performed within each group to compare time points within each group.

## 20. Transformations {#20-transformations}

We don’t plan to perform any transformation for this study.

## 21. Inference criteria {#21-inference-criteria}

We will use p<.05 criteria for determining if the ANOVA results are significant.

P-values will be adjusted by in post-hoc analyses in Tukey's HSD or Bonferroni correction in paired t-tests.

Effect size will be calculated using partial eta squared (ηp²).

## 22. Data exclusion {#22-data-exclusion}

Participants will be informed of eligibility criteria (see [12. Data collection procedures](#12-data-collection-procedures)) before signing up.

We will also exclude any participant who closed the browser at any point when the audio clip is playing.

Participants will not be excluded if they did not complete the rating questions at the end.

## 23. Missing data {#23-missing-data}

If a participant failed to complete all six attention checks, their data will not be included in the analysis.

We will also record the number of dropouts between each time point.

## 24. Exploratory analysis {#24-exploratory-analysis}

We plan to look at how self-reported attention and information retention (on Likert scales) correlates with reaction time and accuracy of attention check questions.

We also expect to see some impact of previous knowledge, personal preference of content, and experience with speed listening on attention.

# Other {#other}

## 25. Other {#25-other}

This pre-registration is submitted as part of course evaluation of PNB 3EE3 in winter term of 2024/25.

# References
