---
title: 'README: Speed Listening'
output: 
  html_document:
    keep_md: true
date: "2025-03-14"
editor_options: 
  markdown: 
    wrap: 72
---

# Speed Listening Experiment

This is an instruction to the files in experimentCode, for the web-based
experiment on speed listening.

## Author

Amy Zhang

## Experiment design

This is a between-participant experiment. The purpose of this study is
to examine how people's attention and listening behaviours change based
on the playback speed of the audio.

Once participants click into the experiment, they will be randomly
assigned to one of the 4 conditions, each with a different audio speed
level (1.0x, 1.5x 1.7x, 2.0x), which will be maintained throughout the
experiment.

The experiment contains the following:

1.  A welcome page

2.  A consent page that requires participants to click consent before
    proceeding

3.  An instruction page telling them what will happen

4.  A test trial with audio clips that repeats until the participants
    are ready to proceed

5.  6 trials with audio clips and multiple choice questions, which add
    up to around 9 minutes in total

6.  An instruction page for the survey

7.  A likert scale survey about their experiences with the experiment
    and speed listening

8.  A thank you page displaying their accuracy result on the multiple
    choice questions

## Materials and Files

This repository contains:

-   "**jspych**": contains all the plugins used in the experiment

-   "**demo.html**": a short demo of the experiment with only 3
    conditions and 3 trials per condition, using shorter audio clips
    that add up to around 3 minutes

-   "**audioclip_demo**": where all the audio clips used in the demo
    experiment can be found

    -   clips are named according to their conditions and trials

    -   e.g. C2T3 means "condition 2 trial 3"

-   "**speedListening.html**": the code for the complete experiment,
    with 4 conditions and 6 trials each

-   "**audioclip**": where all audio clips used in the full experiment
    can be found, audio clips are named in the same way as the demo
    audio clips

## Data

When the participants finish the experiment, a csv file containing the
participants' response will be generated and downloaded to their local
device. Check your browser permission if it didn't download
automatically.

The csv file will be named by whichever condition the participant was
assigned to: "**experiment_data_condition\_[ ].csv**". It will contain
information regarding:

-   "**condition**": the condition assigned to the participant,

-   "**trial_type**": the type of trials,

-   "**knowledge**", "**interest**", "**attention**", "**retention**",
    "**difficulty**", "**frequency**": their response to each likert
    scale question

-   "**overall_accuracy**",

-   "**rt**": the reaction time (measured from when the buttons are
    displayed until the participant made a choice),

-   "**response**": the response to the button presses and likert
    survey),

-   "**trial_number**",

-   "**correct_response**": the correct answers to the multiple choice
    questions

-   "**correct**": whether the participant answered correctly,

-   "**wrong_trial**": the trials where participant answered
    incorrectly.

## Acknowledgments

The "jspsych" repository is downloaded from [jsPsych.org](#0)

All the audio clips and the text script used are generated by ChatGPT.
